### ISSUE TITLE
As a Ken, I want it to be easier for me to send out the notification email to students.

### ISSUE THREAD

**Issue by kenmazaika** [FirehoseCommunity/LightningTalkTopics#17]
Each time I send out a quick reminder about lightning talks to students.  The reminder email looks like this:

![screen shot 2015-09-10 at 2 32 49 pm](https://cloud.githubusercontent.com/assets/233615/9797389/de342408-57c8-11e5-8187-5657fd4fcb9a.png)

Getting the text for the upcoming talks is a bit hard.  This is because the current app lists out each of the students that is assigned, so I have to pay attention to the date:

![ss](https://cloud.githubusercontent.com/assets/233615/9797430/131840c8-57c9-11e5-917d-be198810bf57.png)

Also sometimes I have to dig into the detail page because the description is truncated:

![ss2](https://cloud.githubusercontent.com/assets/233615/9797457/3a654c3e-57c9-11e5-9066-0528c581a9dc.png)
## Here's how we should fix this.

![ss3](https://cloud.githubusercontent.com/assets/233615/9797475/54cba050-57c9-11e5-9107-d9728b88a95a.png)

When a user clicks the link they should be presented a page that includes the roster in a copy & pastable way.  So the following text would be on the page, formatted like this.

> **Continuous Integration** (Faisal)
> What is Continuous Integration? How does it work? And an overview of two of the options out there: Travis CI & CodeShip.
> 
> **Illustrator for Developers** (Mikaila)
> How to quickly get started with Illustrator and apply it to your workflow.
> 
> **Pry for Rails** (Chris McIntyr)
> Pry is a powerful tool that helps debug complex programming problems.  Learn how to use this awesome tool!
> 
> **Scraping With Import.io** (Nehemiah)
> Using Import.io to quickly and efficiently scrape websites to import into your Ruby on Rails app.
> 
> **Vim** (Ben Ricker)
> Vim, a command line editor. Why you should use it? How you should use it? Advantages/ Disadvantages.

**Comment by colinrubbert** [comment]
- As a Colin this would be a valuable resource as well! :joy: 
- I like the idea of having the link for the dates. I was trying to figure out a way to present them in a way that would separate them by date in sections but with the way the code is refactored I'm not entirely sure how to go about i, still wrapping my head around it all since now we're using scopes and partials. I think the link on the date would be an excellent idea and the easiest approach.
- I just added that date section to the cards today so that I could start scheduling talks for the next lightning talks and reduce confusion. 
- What are your thoughts on sending an email out on talk date and send an email to an admin (me) when someone assigns a talk? Automated MailChimp or Rails Mailers?

**Comment by kenmazaika** [comment]
> What are your thoughts on sending an email out on talk date and send an email to an admin (me) when someone assigns a talk? Automated MailChimp or Rails Mailers?

This seems like a cool feature, but probably a different issue.  I'd probably start by using Rails Mailers.

**Comment by colinrubbert** [comment]
Sounds good. I'm working on trying to figure out how to do the scheduled link stuff. That will be a feature by the time the next talks come around for sure. If I'm being honest it will most likely be a feature in the next few days, it's going to bother me if I don't take care of that soon.

**Comment by kenmazaika** [comment]
Haha.  Definitely no rush.  There's plenty of time.  :)

**Comment by colinrubbert** [comment]
It's an interesting learning experience so I'm sure it'll bug me on how to do it until I actually do it.

**Comment by takehiromouri** [comment]
Created a [PR](https://github.com/FirehoseCommunity/LightningTalkTopics/pull/36) to solve this problem :+1:

**Comment by kenmazaika** [comment]
Awesome!
