### ISSUE TITLE
UX Change to brand title in navbar

### ISSUE THREAD

**Issue by amarkpark** [FirehoseCommunity/LightningTalkTopics#44]
I suggest the "brand title" of the navbar should read "Firehose Lightening Talks"

It currently reads "Firehose Project" and that gives two potentially erroneous impressions to users:
1. That the app is PART of the Firehose Project App proper and thus doesn't require signup for folks who already have a FHP login - this is a distinct App with a distinct userbase
2. It appears the link may lead back to the Firehose Project home page rather than back to the Lightening Talks index page

For that brand title to contain "Lightning Talks" is meaningful UX for users.  It will indicate clicking on that link will take them back to the main index of Lightening Talks.

Changing that to "Firehose Lighting Talks" would also agree thematically with the "Firehose Links" nav dropdown.

This is a simple change, and with approval I'd be happy to make it myself.

**Comment by colinrubbert** [comment]
I would agree.

There's two things that I can think of that will be needed to be considered and changed.
1. Do we want to name this `Firehose Talks`, `Firehose Chats` or `Firehose Lightning Talks` 
2. Having it named to `Firehose Lightning Talks` will mean that the navigation break points will need to be changed because of weird breaks in responsiveness. My recommendation here would be to instead of the menu breaking to a hamburger menu at 800px to do it at 1200px. For now that would be a suitable change, I have been thinking about removing the `Firehose Links` navigation item since they are now on the footer (that's for another issue discussion).

I'm more than happy with you taking this on though :smile:

**Comment by amarkpark** [comment]
Other ideas:

Maybe change the text to "Lightening Talks" and count on the iconic FHP drop to carry the Firehose theme?  

Add a little lightening bolt to the water droplet and change the text to "Talks" on the brand side and "Links" on the other side?  (though I think removing that in favor of the footer is cleaner)

As the page stands the only thing that denotes these are "Lightening Talks" at all is the URL.  Is that "Lightening Talks" branding still important?  If so it should be an obvious UI component.

**Comment by kenmazaika** [comment]
Nice!  I love the ideas!

**Comment by amarkpark** [comment]
Speaking of ideas, not that this one should be in THIS issue, but I want to get it recorded before I forget... how about a special section of the idea page dedicated to a "Gem Spotlight" talk... with the intent that at least one talk in every presentation schedule could have a gem spotlight in it where someone shows off a cool gem they've discovered and how it works and what it does...?

**Comment by amarkpark** [comment]
@colinrubbert @kenmazaika I see from reading the contributor guide that forking is the contributor methodology of choice.  I'm used to making feature branches off a shared project repo and I'm not clear on the process of PRing from/with a forked repo.

In the case of a fork would I still make a feature branch or would I just make changes to the master branch of my fork, push to origin master on my fork and then PR by comparing across forks?  Do I need to set the upstream?  (More specifically, do I use the upstream for anything other than pulling down and synching original master changes?)

**Comment by kenmazaika** [comment]
Colin made a detailed write-up of how to do that here:
http://community.thefirehoseproject.com/2015/08/19/How-To-Fork-A-Repo-And-Contribute.html

If you do make a fork, you will need to update your fork from upstream.  In short you'll do:

```
git remote add upstream PASTE-IN-THE-OFFICIAL-GIT-URL
```

Then if you do:

```
git checkout master
git pull upstream master
git push origin master
```

It will update your fork.

**Comment by colinrubbert** [comment]
@amarkpark lets go with just renaming the brand to `Lightning Talks` since we do have the FHP logo next to it. I think we can reduce down to that point w/o losing it's meaning. I like that. 

I'm going to open a different issue to remove the `Firehose Links` from the navigation since we have all the links in the footer.

As far as doing PRs it's nearly exactly the same as a regular PR. I would also recommend that you create a feature branch with your forked repo since once you open PR it will have that feature branch name. It just makes it a bit cleaner.

**Comment by amarkpark** [comment]
OK... I'm getting ready to fork now and I'll change the brand text.
